title: "zFragment's Blog"
author: zFragment
email: nooberzinbr@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello! We do hope you enjoy this blog, as this is my first one.
  As you can see, the site is open source, so anything you do I'll get to see it! 
  Please consider contributing if you think this can be better.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  zFragment # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
